version: "3.7"
services:
  app:
    build:
      args:
        user: balwant
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel9
    container_name: laravel9-app
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - laravel9

  nginx:
    image: nginx:alpine
    container_name: laravel9-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/conf.d:/etc/nginx/conf.d
    networks:
      - laravel9

networks:
  laravel9:
    driver: bridge
