version: "3.7"
services:
  app:
    build:
      args:
        user: "simform"
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel9
    container_name: laravel9-app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - mysql
    networks:
      - laravel9

  nginx:
    image: nginx:alpine
    container_name: laravel9-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel9

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
        - laravel9
    volumes:
        - 'laravel-mysql:/var/lib/mysql'

networks:
  laravel9:
    driver: bridge
volumes:
    laravel-mysql:
        driver: local
